[package]
name = "fianco_brain"
version = "0.1.0"
edition = "2021"

[lib]
name = "fianco_brain"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.2", features = ["extension-module"] }
numpy = "0.16.0"